apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-delete
  annotations:
    helm.sh/hook: pre-delete
    # helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-delete-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "exit", "-1"]
